POST http://localhost:3000/campaigns

{
    "name": "change",
    "content": "change password",
    "emails": ["testego@teste.com.br","testego2@teste.com.br","testego3@teste.com.br"]
}

###
GET http://localhost:3000/campaigns/cqf66l324q4jf50v04eg

###
DELETE http://localhost:3000/campaigns/delete/cqf6ncb24q4jp825vc90