@url = http://localhost:3000

@identity_provider = http://localhost:8080

POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
    "name": "change",
    "content": "change password",
    "emails": ["testego@teste.com.br","testego2@teste.com.br","testego3@teste.com.br"]
}

###
GET {{url}}/campaigns/
Authorization: Bearer {{access_token}}

###
PATCH {{url}}/campaigns/cancel
Authorization: Bearer {{access_token}}

###
DELETE {{url}}/campaigns/delete/
Authorization: Bearer {{access_token}}

###
# @name token
POST {{identity_provider}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=gustavo@gmail.com&password=vaporesso230895&grant_type=password

###
@access_token = {{token.response.body.access_token}}