@url = http://localhost:3000
@identity_provider = http://localhost:8080

###
# @name campaign_create
POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
    "name": "Hi teste gustavo!",
    "content": "Hello!",
    "emails": ["teste@teste.com"]
}

###
@campaign_id = {{campaign_create.response.body.id}}

###
GET {{url}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
PATCH {{url}}/campaigns/start/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
DELETE {{url}}/campaigns/delete/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
# @name token
POST {{identity_provider}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=gustavo@gmail.com&password=vaporesso230895&grant_type=password

###
@access_token = {{token.response.body.access_token}}